name: ARMV7 Build

on: [push, pull_request]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7
    steps:
      - uses: actions/checkout@v2.1.0
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          # target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04
          
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
            --volume "~/.cargo:~/.cargo"

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          
          install: |
            apt-get update -q -y
            apt-get install cmake openssl libssl-dev pkg-config curl -q -y
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env

          run: |
            source $HOME/.cargo/env
            cargo build --release
            cp target/release/rust_lumibaer /artifacts
            pwd

      - name: Get the output
        run: |
          ls -la
          pwd

      - uses: actions/upload-artifact@v3
        with:
          name: armv7_build
          path: artifacts/rust_lumibaer
